#!/usr/bin/env bash
# test-careful-guard-safe-out.sh
# `out` belongs in the safe-artifact set, and only as an exact basename.
#
# Measured over ~/.claude/watch-hooks.log — 176 real Bash permission prompts over
# six days — `rm -rf out && npm run build` was 43 of them: 24% of EVERY prompt,
# the single largest interruption source. `out` is the Next.js static export dir;
# the content is regenerated by the very next command in the same line.
#
# The carve-out is basename-scoped like every other SAFE entry, so this pins both
# directions: `out` is silent, anything merely STARTING with it is not.
set -uo pipefail
# Resolved BEFORE the cd: `$0` is relative, so a `dirname "$0"` read
# afterwards points at the new cwd. Sourcing then silently found
# nothing, `check` was undefined, and the suite exited 0 with fail=0 -
# a false PASS in the files that exist to prevent one.
_HERE=$(cd "$(dirname "$0")" && pwd) || exit 1
cd "$_HERE/.." || exit 1

# shellcheck disable=SC2034  # read by the sourced harness below
GUARD="hooks/gate-scripts/careful-guard.sh"

pass=0 fail=0

# bypassPermissions: every check is live there, so nothing below is masked by
# the auto-mode stand-down.
# shellcheck source=tests/lib/careful-guard-harness.sh
# shellcheck disable=SC1091  # the source= path above needs `shellcheck -x`
. "$_HERE/lib/careful-guard-harness.sh" || exit 1

echo "--- out is a build artifact (must be silent) ---"
# The exact shape that was 24% of all prompts.
check "rm -rf out && build"          allow 'rm -rf out && npm run build'
check "leading ./"                   allow 'rm -rf ./out'
check "trailing slash"               allow 'rm -rf out/'
check "nested under a project"       allow 'cd /Volumes/Work/Projects/chrisyau.me && rm -rf out'
check "alongside another safe dir"   allow 'rm -rf out dist .next'

echo "--- basename match only (must still warn) ---"
check "output is NOT out"            ask   'rm -rf output'
check "out-of-tree is NOT out"       ask   'rm -rf out-backup'
check "a file named out.tar"         ask   'rm -rf out.tar'
# `out` is generic enough to be real data outside a project tree, so the carve-out
# is relative-only: the basename alone must not clear an absolute path.
check "absolute /important/out"      ask   'rm -rf /important/out'
check "home-anchored ~/out"          ask   'rm -rf ~/out'
check "absolute project out"         ask   'rm -rf /Volumes/Work/Projects/chrisyau.me/out'
# Any path component at all disqualifies it — the guard cannot resolve where the
# path lands, and an unexpanded $VAR is unknowable by construction.
check "parent-relative ../out"       ask   'rm -rf ../out'
check "subdir path sub/out"          ask   'rm -rf packages/app/out'
# shellcheck disable=SC2016  # $HOME must reach the guard UNexpanded — that is the case
check 'unexpanded $VAR/out'          ask   'rm -rf "$HOME/out"'
check "an unsafe sibling in the same command" ask 'rm -rf out && rm -rf /etc/nginx'

echo
echo "passed=$pass failed=$fail"
[[ $fail -eq 0 ]]
